### ISSUE TITLE
Concurrency concerns (question not issue)

### ISSUE THREAD

**Issue by ramonsaraiva** [matthiask/django-tree-queries#38]
hey @matthiask - I recently landed on this library (great job, btw) after having multiple issues related to concurrency when using `django-mptt`.. what initally brought me here was an unresolved issue (and the library becoming unmaintained) about `tree_id`.

`django-mptt` uses `max(tree_id) + 1` to assign a `tree_id` to a new node and this doesn't play well with concurrent writes..

i know it's a broad question, but overall, would you recommend using this library considering we're going to have multiple workers doing concurrent writes to nodes that can possibly live in the same tree? i haven't gone too deep in the implementation (although i probably will as you said that sloc is ~280 lines).. but wondering your opinion on that?

cheers

**Comment by matthiask** [comment]
Hi @ramonsaraiva 

I'd definitely recommend using this library when you have concurrent writes *if the recursive CTE approach performs well enough*. Disqus also used recursive CTEs in the past and databases have become much faster since then so it should be fine. It will quite definitely be fine for trees with hundreds or thousands of nodes (or maybe even much more) but you have to try it out to be sure.

The advantage of django-tree-queries is that there's no redundant information in the database which can get out of sync; the only problem you may encounter is if you're creating loops in the data structure. The [SQL](https://github.com/matthiask/django-tree-queries/blob/8863c5237f32585cc5ddc21041231155cb806149/tree_queries/compiler.py#L69-L94) will loop infinitely in this case.

**Comment by ramonsaraiva** [comment]
thanks for the lightning speed response!

that's great to hear, I think it should work well performance wise as our trees will have big depths.. not expecting a lot of siblings as well, but we'll definitely have millions of different trees.. that shouldn't be a problem.

closing!
